			var eids = "";
			var subsenabled = true;
			var supportstabpanel = true;
			var hashomebutton = true;
			var newarchivepanel;
			var preventswitching = false;
			var segButtons;
			var paperheight;
			var overlaysettingspopup;
			var infopanel;
			var actions;
			var linkstore;
			var linkssaved;
			var editionguid;
			var fontsize = 14;
			var pnlArchive;
			var toolArchive;
			var videoscontainer;
			var readytoshowarchive = "";
			var hasinitarchive = false;
			var archivecontainer = "";
			var totalarchiveheight = 0;
			var devicemultiple = 0;
			var Searchboxsmall = 0;
			var searchtype = 'p';
			var offlineprepath = "/media/internal/pagesuite/apps/";
			var termsurl = "http://www.google.com";
			var privacyurl = "http://www.yahoo.com";
			var faqurl = "http://www.bbc.co.uk";
			var targetos = "android";
			var imagelogo = "Express_logo.png";
			var serverprefix = "http://html5.pagesuite-professional.co.uk/";
			var tempxml = "";
			var videostore;
			var moving = false;
			var savedtickets = "";
			var initsearch = false;
			var listresults;
			var showarchive = false;
			var buttonindex = 0;
			var restorepaper = false;
			var searchsegmentedButton;
			var ignoreinitofedition = false;
			var isfromdownload = false;
			var firstdownloadview = false;
			var archivecontainerlive = "";
			var dontdownloadagain = false;
			var searchstore = "";
			var hasdownloaded = false;
			var hasinitilised = false;
			var downloadcount = 0;
			var downloaditem = 1;
			var onlineoptionsstore;
			var HPApp;
			var popup;
			var pnlSearch;
			var timeoutpopup;
			var popupfinished;
			var timeoutpopupfinished;
			var overlaypdf1;
			var lblpdfpages = "";
			var downloadaction = 1;
			var pagestore;
			var shoulddownload = false;
			var downloadlbleditionguid;
			var downloadlblname;
			var downloadnopages;
 			var heights = 1;
 			var pnlPaper;
			var pnlDownloads;
			var toolDownload;
			var disableresize = false;
			var pnlLoader;
			var isEditing = false;
			var htmlcontainer = "";
			var pnlMain;
			var pnlHome;
			var pnlSettings;
			var toolSettings;
			var panel;
			var timeouthome;
			var timeoutreader;
			var pagecontainer = "";
			var phonemode = false;
			var lblpages = "";
			var optionsstore;
			var lbleditionguid = "";
			var lblname = "";
			var lbleditions = "";
			var lblpagespdf = "";
			var lblpageheight = "";
			var lblpagewidth = "";
			var lblpageratio = "";
			var onlinenormalfilepath = "http://edition.pagesuite-professional.co.uk/get_image.aspx?h=[h]&eid=[edition]&pnum=[page]";
			var onlinezoomfilepath = "[edition]/[page]/zoom.jpg";
			var offlinenormalfilepath = "[edition]/[page]/page.jpg";
			var offlinezoomfilepath = "[edition]/[page]/zoom.jpg";
			var editionpath = serverprefix + "editions.aspx?maxnumber=10000&publicationguid=[GUID]";
			var pubguid = "53b429fb-3408-43be-8ec3-5056c7e13022";
			var lblpubname = "Newsday";
			var lbldimensionpath = "[edition].xml";
			var hascreatedreader = false;
			var lblpagepath = "";
			var changingarchive;
			var buttonsGroup2;
			var startdownloading = false;
			var overlay;
			var btnmenu;
			var btnpages;
			var btnarchive;
			var btnforward;
			var btnfastforward;
			var btnbackward;
			var btnfastbackward;
			var txtpagenumber;
			var searchpanel;
			var Searchbox;
			var splashpanel;
			var tabpanel;
			var settingspanel;
			var downloadpanel;
			var archivepanel;
			var paperpanel;
			var panelsubpanel1;
			var panelsubpanel2;
			var panelsubpanel3;
			var ignorecardswitch = false;
			var oldcardno;
			var zoominnow = false;
			var nopages;
			var pdfstore;
			var editionspath;
			var editionstore;
			var pagestore;
			var tbar;
			var widths;
			var heightofpanel;
			var listview;
			var listeditions;
			var segmentedButton;
			var listpages;
			var pagenumber;
			var pageno = 1;
			var nextpageno = 0;
			var delayedTask;
			var delayedTask2;
			var zoomedinview;
			var imgcache;
			var iszoomedin = false;
			var carind1 = -1;
			var carind2 = -1;
			var carind3 = -1;
			var cache1pageno = 0;
			var cache1 = new Image();
			var cache1isloaded = false;
			var cache1pagenoland = 0;
			var cache1land = new Image();
			var cache1isloadedland = false;
			var cache2pageno = 0;
			var cache2 = new Image();
			var cache2isloaded = false;
			var cache2pagenoland = 0;
			var cache2land = new Image();
			var cache2isloadedland = false;
			var cache3pageno = 0;
			var cache3 = new Image();
			var cache3isloaded = false;
			var cache3pagenoland = 0;
			var cache3land = new Image();
			var cache3isloadedland = false;
			var cacheindex = 0;
			var oldportpageno = 0;
			var dtapzoom;
			var mtapzoom;
			var enableweblinks;
			var startbackpage;
			
			getSettings();
			
			function getSettings(){
				dtapzoom =  localStorage.getItem("hp.dtapzoom") ? localStorage.getItem("hp.dtapzoom"): 5; // double tap zoom level
				mtapzoom = localStorage.getItem("hp.mtapzoom") ? localStorage.getItem("hp.mtapzoom"): 5;// 			
				enableweblinks: localStorage.getItem("hp.enableweblinks") ? localStorage.getItem("hp.enableweblinks"): true; // enable weblinks when zoomed
				startbackpage =  localStorage.getItem("hp.startbackpage") ? localStorage.getItem("hp.startbackpage"): false; // start from back page
			}
